1/ Video annotation system :
    - option to capture the current frame from the Video
    - the video pauses and current frame opens with draw/write features
    - after clicking save, it's sent to db and saved
    - a mark appears on the slider and clicking it gives preview of the image
    - clicking it opens the image with each thing intact -> text is text, drawing is drawing

2/ Dynamic resume generator extension :
    - has our resume beforehand in pdf
    - Reads js, checks company name
    - fetches interview experiences related to that and takes imp keywords
    - mix and match these keywords and jd keywords and suggest resume iteration
    - download option directly with renaming features